### PR TITLE
Added filter for WordPress logins on Apache

### PR DESCRIPTION
**Pull request by mvdriel**

### CODE REVIEW

**Comment by tersmitten** [comment]
Great addition, but wouldn't it be more flexible when `copy.src` (`copy filters` task) is configurable (through the optional variable `fail2ban_filterd_path`). That way there's no need to include all the filters in this role.

@mvdriel What do you think?

**Comment by mvdriel** [comment]
@tersmitten Good idea. I will update the pull request.

**Comment by mvdriel** [comment]
@ What do you think of this update?

**Comment by tersmitten** [comment]
@mvdriel Does copy work when there are conflicting files in the destination?

**Comment by mvdriel** [comment]
@tersmitten It will overwrite conflicting files (default behaviour of copy).

**Comment by tersmitten** [comment]
@mvdriel Do you see any use for specifying multiple directories?

**Comment by mvdriel** [comment]
@tersmitten Yes, for example when you want to use the filters inside this role and some of your own.

**Comment by tersmitten** [comment]
@mvdriel Ok, but I rather not have any filters inside this role :-)

**Comment by tersmitten** [comment]
@mvdriel I'd rather store that in another repository (or folder in an existing one)

**Pull request merged**
