### PR TITLE
Fix action variable in template

### LINKED ISSUE #20: Cannot pass action variables due to template issue
In the jail.local template, the `fail2ban_action` variable is wrapped with `%( ... )s`.  This should not be the case - it is inconsistent with the way fail2ban_banaction is handled, but more importantly it prevents action parameters from being passed.  Action parameters are added in square-brackets, and often contain individual python variables that are individually wrapped in `%( )`.  See http://serverfault.com/a/629568 for a description.

The problem with fixing this is that the change will be backwards-breaking.  Users should always have been including the `%( )` in their `fail2ban_action` vars themselves, but will have had to strip them because the template includes them.

The fix is simple.  But it would need highlighting in the docs so that people will see it straight away if they update and wonder why fail2ban won't start any more :)

### PR DESCRIPTION
**Pull request by j4m3s**
Fixes #20

### CODE REVIEW

**Comment by tersmitten** [comment]
Do you think:

```
# The simplest action to take: ban only
action_ = %(banaction)s[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]

# ban & send an e-mail with whois report to the destemail.
action_mw = %(banaction)s[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
              %(mta)s-whois[name=%(__name__)s, dest="%(destemail)s", protocol="%(protocol)s", chain="%(chain)s"]

# ban & send an e-mail with whois report and relevant log lines
# to the destemail.
action_mwl = %(banaction)s[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
               %(mta)s-whois-lines[name=%(__name__)s, dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s"]
```

should also be changed?

**Comment by j4m3s** [comment]
Sorry @tersmitten I'm a bit rusty - which bit should be changed?

**Comment by tersmitten** [comment]
The expansion of `%(banaction)s` in `jail.local.j2`

**Comment by j4m3s** [comment]
No I think that's correct (as you pasted) - `banaction` should be expanded as it goes into `action_`.  `%(xyz)` is just like `{$xyz}` in php and it needs to be expanded inside `action_` otherwise we'll be left with just a "banaction" string.

Sorry if I misunderstood the question :)

**Pull request closed without merging**
